version: '3.8'

services:

  # Backend API
  smart-eyes-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-eyes-api
    environment:
      POSTGRES_USER: patrick
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smart-eyes-docker
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/smart-eyes-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: patrick
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smart-eyes-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
    

    